title: DNS
description: DNS (Domain Name System) is the distributed naming system that translates
  human-readable domain names (like example.com) into the numerical IP addresses computers
  use to communicate. It functions as the internet's phone book, enabling users to
  access websites and services using memorable names instead of numeric addresses.
url: https://dns.apievangelist.com
collections:
  api_stories:
    output: false
exclude:
- README.md
- Gemfile
- Gemfile.lock
- Dockerfile
- examples
- json-ld
- json-schema
- json-structure
- vocabulary
